apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: streaming
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-role
  namespace: streaming
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "services"]
    verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  namespace: streaming
subjects:
  - kind: ServiceAccount
    name: flink
    namespace: streaming
roleRef:
  kind: Role
  name: flink-role
  apiGroup: rbac.authorization.k8s.io
