apiVersion: v1
kind: Namespace
metadata:
  name: streaming
  labels:
    app.kubernetes.io/part-of: streaming-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/part-of: streaming-platform
